apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: fintex.ktm.yetiappcloud.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-demo-service
                port:
                  number: 80
