apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-demo
  template:
    metadata:
      labels:
        app: frontend-demo
    spec:
      containers:
        - name: frontend-demo-container
          image: your-frontend-image:latest
          env:
            - name: REACT_APP_BASE_URL
              value: "http://backend-demo-service/"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-demo-service
spec:
  selector:
    app: frontend-demo
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP