---
- name: Deploy Nginx Configuration
  hosts: 159.89.173.99
  become: yes
  tasks:
    - name: Copy nginx.conf file
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded