---
- name: Install Docker and Dependencies
  hosts: 192.168.0.1
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker CE, Docker CLI, and containerd.io
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install pip (Python package manager)
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == 'Debian'

    - name: add userpermissions
      shell: "usermod -aG docker ubuntu"

    - name: Install Docker Python SDK using pip
      become_user: ubuntu
      pip:
        name: 
          - docker
          - docker-compose
        state: present
        executable: pip3
